In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../employees_salary.csv")
df

       员工编号    姓名   部门  工资(元)
0   EMP0008    李涛  产品部   5582
1   EMP0018    高娟  产品部  14861
2   EMP0034   赵娟军  产品部  16470
3   EMP0040    朱明  产品部   4921
4   EMP0046    罗芳  产品部  24540
5   EMP0007    赵军  人事部  29447
6   EMP0013    黄丽  人事部  23971
7   EMP0017    刘磊  人事部  27478
8   EMP0021    马慧  人事部  21128
9   EMP0022    张敏  人事部  28185
10  EMP0023   陈涛伟  人事部  19403
11  EMP0024    陈超  人事部  23937
12  EMP0041   马洋涛  人事部  16861
13  EMP0047    高华  人事部   9693
14  EMP0002    刘敏  市场部  22349
15  EMP0006   杨勇敏  市场部  15449
16  EMP0015    李勇  市场部   9913
17  EMP0019    黄静  市场部  27765
18  EMP0020   陈娟慧  市场部  15608
19  EMP0035    胡芳  市场部   4986
20  EMP0036    马勇  市场部  11147
21  EMP0038    陈洋  市场部  17520
22  EMP0044    郭娜  市场部  22498
23  EMP0049    王伟  市场部   5400
24  EMP0003   杨磊超  技术部  21390
25  EMP0014    何磊  技术部  10505
26  EMP0025  孙丽秀英  技术部  22626
27  EMP0026   孙艳磊  技术部  10892
28  EMP0030   黄娜勇  技术部  22277
29  EMP0031    何磊  技术部   5326
30  EMP0042   吴强芳  技术部  27509
31  EMP0004   杨秀英  行政部  22309
32  EMP0033    林强  行政部  10962
33  EMP0001    赵伟  财务部  10314
34  EMP0010   黄艳娜  财务部   6309
35  EMP0028   郭慧娟  财务部  20671
36  EMP0032   李勇娜  财务部  12125
37  EMP0039   何伟娜  财务部   8449
38  EMP0045    王磊  财务部  21970
39  EMP0009    何艳  运营部  21918
40  EMP0011    马洋  运营部   8329
41  EMP0029    杨艳  运营部  17355
42  EMP0048   刘艳涛  运营部  27637
43  EMP0005    周伟  销售部  25876
44  EMP0012   周娜慧  销售部  20502
45  EMP0016   林杰涛  销售部  11679
46  EMP0027  林娜秀英  销售部   7207
47  EMP0037    杨强  销售部  16824
48  EMP0043   林超超  销售部   4863
49  EMP0050    何强  销售部  14436

In [10]:
# 分箱
pd.cut(df['工资(元)'], bins=2)
print(pd.cut(df['工资(元)'], bins=2).value_counts())

4863
29447
工资(元)
(4838.416, 17155.0]    26
(17155.0, 29447.0]     24
Name: count, dtype: int64

In [17]:
# 自定义区间
df['工资区间'] = pd.cut(df['工资(元)'], bins=[3000, 10000, 20000, 30000], labels=['低', '中', '高'])
df['工资区间']

工资区间
高    21
中    17
低    12
Name: count, dtype: int64

In [19]:
# 区间等频率的分割
pd.qcut(df['工资(元)'], q=3).value_counts()

工资(元)
(4862.999, 11324.333]    17
(21742.0, 29447.0]       17
(11324.333, 21742.0]     16
Name: count, dtype: int64

In [30]:
df.reset_index(inplace=True)
df.set_index('员工编号',inplace=True)
df

         index    姓名   部门  工资(元) 工资区间
员工编号
EMP0008      0    李涛  产品部   5582    低
EMP0018      1    高娟  产品部  14861    中
EMP0034      2   赵娟军  产品部  16470    中
EMP0040      3    朱明  产品部   4921    低
EMP0046      4    罗芳  产品部  24540    高
EMP0007      5    赵军  人事部  29447    高
EMP0013      6    黄丽  人事部  23971    高
EMP0017      7    刘磊  人事部  27478    高
EMP0021      8    马慧  人事部  21128    高
EMP0022      9    张敏  人事部  28185    高
EMP0023     10   陈涛伟  人事部  19403    中
EMP0024     11    陈超  人事部  23937    高
EMP0041     12   马洋涛  人事部  16861    中
EMP0047     13    高华  人事部   9693    低
EMP0002     14    刘敏  市场部  22349    高
EMP0006     15   杨勇敏  市场部  15449    中
EMP0015     16    李勇  市场部   9913    低
EMP0019     17    黄静  市场部  27765    高
EMP0020     18   陈娟慧  市场部  15608    中
EMP0035     19    胡芳  市场部   4986    低
EMP0036     20    马勇  市场部  11147    中
EMP0038     21    陈洋  市场部  17520    中
EMP0044     22    郭娜  市场部  22498    高
EMP0049     23    王伟  市场部   5400    低
EMP0003     24   杨磊超  技术部  21390    高
EMP0014     25    何磊  技术部  10505    中
EMP0025     26  孙丽秀英  技术部  22626    高
EMP0026     27   孙艳磊  技术部  10892    中
EMP0030     28   黄娜勇  技术部  22277    高
EMP0031     29    何磊  技术部   5326    低
EMP0042     30   吴强芳  技术部  27509    高
EMP0004     31   杨秀英  行政部  22309    高
EMP0033     32    林强  行政部  10962    中
EMP0001     33    赵伟  财务部  10314    中
EMP0010     34   黄艳娜  财务部   6309    低
EMP0028     35   郭慧娟  财务部  20671    高
EMP0032     36   李勇娜  财务部  12125    中
EMP0039     37   何伟娜  财务部   8449    低
EMP0045     38    王磊  财务部  21970    高
EMP0009     39    何艳  运营部  21918    高
EMP0011     40    马洋  运营部   8329    低
EMP0029     41    杨艳  运营部  17355    中
EMP0048     42   刘艳涛  运营部  27637    高
EMP0005     43    周伟  销售部  25876    高
EMP0012     44   周娜慧  销售部  20502    高
EMP0016     45   林杰涛  销售部  11679    中
EMP0027     46  林娜秀英  销售部   7207    低
EMP0037     47    杨强  销售部  16824    中
EMP0043     48   林超超  销售部   4863    低
EMP0050     49    何强  销售部  14436    中