In [1]:
import pandas as pd

### 数据的变形

In [33]:
data = {
    'ID':[1,2],
    'Name':['Alice','Bob'],
    'Math':[80,90],
    'English':[74,80],
    'Science':[85,92],
    'History':[78,88],
    'Geography':[75,85]
}
df = pd.DataFrame(data)
df

   ID   Name  Math  English  Science  History  Geography
0   1  Alice    80       74       85       78         75
1   2    Bob    90       80       92       88         85

In [4]:
#转置
df.T

               0    1
ID             1    2
Name       Alice  Bob
Math          80   90
English       74   80
Science       85   92
History       78   88
Geography     75   85

In [17]:
#宽表-->长表
df2 = df.melt(id_vars=['ID','Name'],value_vars=['English','Science',"History","Geography"],var_name="科目",value_name="分数").sort_values('ID')
df2

   ID   Name         科目  分数
0   1  Alice    English  74
2   1  Alice    Science  85
4   1  Alice    History  78
6   1  Alice  Geography  75
1   2    Bob    English  80
3   2    Bob    Science  92
5   2    Bob    History  88
7   2    Bob  Geography  85

In [25]:
#长表-->宽表
df2.pivot(index=['ID',"Name"],columns=["科目"],values="分数")

科目        English  Geography  History  Science
ID Name
1  Alice       74         75       78       85
2  Bob         80         85       88       92

In [59]:
#分列，把Name列中的值 取首字母作为一列，最后一个字母作为一列
df['First_Letter'] = df['Name'].str[0]
df['Last_Letter'] = df['Name']
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            2 non-null      int64
 1   Name          2 non-null      str
 2   Math          2 non-null      int64
 3   English       2 non-null      int64
 4   Science       2 non-null      int64
 5   History       2 non-null      int64
 6   Geography     2 non-null      int64
 7   First_Letter  2 non-null      str
 8   Last_Letter   2 non-null      str
dtypes: int64(6), str(3)
memory usage: 276.0 bytes