In [1]:
import pandas as pd

### 场景:某公司销售数据如下，请完成以下任务:
1.计算每种产品[总销售额(销售额=单价销量)。
2.找出销售额最合的产品。
3.按销售额从高到低排序，并输出所有产品信息。

In [2]:
data = {
    '产品名称': ['A', 'B', 'C', 'D'],
    '单价': [100, 150, 200, 120],
    '销量': [50, 30, 20, 40]
}

df=pd.DataFrame(data)
df

  产品名称   单价  销量
0    A  100  50
1    B  150  30
2    C  200  20
3    D  120  40

In [6]:
# 计算每种产品[总销售额(销售额=单价销量)。
df['总销售额'] = df['单价'] * df['销量']
df

  产品名称   单价  销量    总价  总销售额
0    A  100  50  5000  5000
1    B  150  30  4500  4500
2    C  200  20  4000  4000
3    D  120  40  4800  4800

In [8]:
#找出销售额最合的产品。
df.nlargest(1,'总销售额')

  产品名称   单价  销量    总价  总销售额
0    A  100  50  5000  5000

In [10]:
#按销售额从高到低排序，并输出所有产品信息。
df.sort_values(['总销售额'],ascending=False)

  产品名称   单价  销量    总价  总销售额
0    A  100  50  5000  5000
3    D  120  40  4800  4800
1    B  150  30  4500  4500
2    C  200  20  4000  4000