In [6]:
import pandas as pd

### 案例1:学生成绩分析
场景:某班级的学生成绩数据如下，请完成以下任务:
1.计算每位学生的总分和平均分。
2.找出数学成绩高于90分或英语成绩高于85分的学生。
3.按总分从高到低排序，并输出前3名学生。

In [8]:
data = {'姓名': ['张三', '李四', '王五', '赵六', '钱七'],
        '数学': [85, 92, 78, 88, 95],
        '英语': [90, 88, 85, 92, 80],
        '物理': [75, 80, 88, 85, 90]
        }
df = pd.DataFrame(data)
df

   姓名  数学  英语  物理
0  张三  85  90  75
1  李四  92  88  80
2  王五  78  85  88
3  赵六  88  92  85
4  钱七  95  80  90

In [23]:
# 计算总分和平均分
df['总分'] = df[['数学', '英语', '物理']].sum(axis=1)
df['平均分'] = df[['数学', '英语', '物理']].mean(axis=1)
df

   姓名  数学  英语  物理   总分        平均分
0  张三  85  90  75  250  83.333333
1  李四  92  88  80  260  86.666667
2  王五  78  85  88  251  83.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333

In [24]:
# 找出数学成绩高于90分或英语成绩高于85分的学生
df[(df['数学']>90) | (df['英语']>85)]

   姓名  数学  英语  物理   总分        平均分
0  张三  85  90  75  250  83.333333
1  李四  92  88  80  260  86.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333

In [26]:
#按总分从高到低排序，并输出前3名学生
df.sort_values(['总分'],ascending=False).head(3)

   姓名  数学  英语  物理   总分        平均分
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
1  李四  92  88  80  260  86.666667