In [1]:
import pandas as pd

### 常用的一些方法

In [5]:
df = pd.DataFrame(
    {
        "A": [1, 2, 3, 4,5,6,7,8,9,10],
        "B": [10, 9, 8, 7,6,5,4,3,2,1],
        "C": [1, 1, 1, 1,1,1,1,1,1,1],
        "D": [1, 2, 3, 4,5,6,7,8,9,10],
    }
)
df

    A   B  C   D
0   1  10  1   1
1   2   9  1   2
2   3   8  1   3
3   4   7  1   4
4   5   6  1   5
5   6   5  1   6
6   7   4  1   7
7   8   3  1   8
8   9   2  1   9
9  10   1  1  10

In [6]:
# 取前n条
df.head(1)

   A   B  C  D
0  1  10  1  1

In [7]:
# 取后n条
df.tail(1)

    A  B  C   D
9  10  1  1  10

In [8]:
# 是否包含
df.isin([1])

       A      B     C      D
0   True  False  True   True
1  False  False  True  False
2  False  False  True  False
3  False  False  True  False
4  False  False  True  False
5  False  False  True  False
6  False  False  True  False
7  False  False  True  False
8  False  False  True  False
9  False   True  True  False

In [9]:
# 是否为NaN
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False
6  False  False  False  False
7  False  False  False  False
8  False  False  False  False
9  False  False  False  False

In [21]:
# sum求和
df['C'].sum()

A    10
B    10
C     1
D    10
dtype: int64

In [22]:
# 最大值
df.max()

A    10
B    10
C     1
D    10
dtype: int64

In [24]:
# 平均数
df.mean()

A    5.5
B    5.5
C    1.0
D    5.5
dtype: float64

In [25]:
# 中位数
df.median()

A    5.5
B    5.5
C    1.0
D    5.5
dtype: float64

In [28]:
# 众数
df['A'].mode()

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: A, dtype: int64

In [34]:
# 标准差/方差
print(f"方差:{df['A'].var()}")
print(f"标准差:{df['A'].std()}")

方差:9.166666666666666
标准差:3.0276503540974917

In [39]:
# 重复值
print(df.value_counts())
print(df.A.value_counts())
print("去重")
df.drop_duplicates()
print("检查是否有重复的")
df.duplicated(subset='A')

A   B   C  D
1   10  1  1     1
2   9   1  2     1
3   8   1  3     1
4   7   1  4     1
5   6   1  5     1
6   5   1  6     1
7   4   1  7     1
8   3   1  8     1
9   2   1  9     1
10  1   1  10    1
Name: count, dtype: int64
A
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
Name: count, dtype: int64
去重
检查是否有重复的

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [40]:
# 替换
df.replace(10,20)

    A   B  C   D
0   1  20  1   1
1   2   9  1   2
2   3   8  1   3
3   4   7  1   4
4   5   6  1   5
5   6   5  1   6
6   7   4  1   7
7   8   3  1   8
8   9   2  1   9
9  20   1  1  20

In [43]:
# 累积和
df.cumsum()
# 累积最大
df.cummax()

    A   B  C   D
0   1  10  1   1
1   2  10  1   2
2   3  10  1   3
3   4  10  1   4
4   5  10  1   5
5   6  10  1   6
6   7  10  1   7
7   8  10  1   8
8   9  10  1   9
9  10  10  1  10

In [49]:
# 排序
df.sort_index(ascending=False)

df.sort_values(['A','B'],ascending=False)

    A   B  C   D
9  10   1  1  10
8   9   2  1   9
7   8   3  1   8
6   7   4  1   7
5   6   5  1   6
4   5   6  1   5
3   4   7  1   4
2   3   8  1   3
1   2   9  1   2
0   1  10  1   1

In [51]:
# 获取最大的N条
df.nlargest(2,['A','B'])

# 获取最小值

df.nsmallest(2,['A'])

   A   B  C  D
0  1  10  1  1
1  2   9  1  2